sudo: required
dist: trusty
language: c
addons:
  apt:
    packages:
    - binutils-arm-none-eabi
    - gcc-arm-none-eabi
script: make all
before_deploy: make dist
deploy:
  provider: releases
  api_key:
    secure: VlQxillHbvEjhZUfkacghbRKDJTXkDUJ8QrASRdFWMsDZIp3vJiPZJpa7ipkFqtnUwDw5qG+w7sdoUBA6At5vdzBphBcLjD8OJAb7zXH1wiGc3V1VW+R0h35d+kJeWziq0gwzSZ/ms+v7DMbr4jODksiLYDkRDRI30wu+6SRTk6R7dS/fbc6iCGmoELSFseMFUJV0ZkIDORm2hrru/Y+Yp0Y9gWRDlNRSgqtkGaNYxXksbG5wvqbCWgRUDL4L0XDCpQb4n30CbLaBLZSd5VH/gbh0k2/YWnfholi7YtPKxUYFxvzZDysFD58O5ShDzM2DFG5XZiyUo/nL9e0SbtPHpxt29q2dK0d0WyMldoIh5bEiHZliEW/oMByYEzMPRXbzqMNWIgI6FKOAPne710HlBSCe8VBDubE37237e181E2z8LG/m+UkjKT1pd0+3v+e8pl8Ko89F1DiQSbdwJIkquhKozyiNVCtjS/w2OC1d2x5kqYrynK/X7zuFQUvWdmzA1dohmlsBIPsc3kYxFPTbS81/IviTSWBeqMg2QIcgqUZVz4w9ZBJKBD2ZxDLMrlBHPJdfZEoAu+xxdyddgZHYgWGOv5kLeVPim2XXj7PzwYYH7ox2KMwIKlLZrWEbzbtyRu3VFWsMrpGvU6BpqBJLH4KUn3aNP0ehHZu5PhSDYU=
  file: dist/*.tar.gz
  file_glob: true
  skip_cleanup: true
  on:
    repo: ReservedField/arm-compiler-rt
    tags: true
